import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NextAuthProvider } from "@/components/NextAuthProvide";
import { getServerAuthSession } from "@/server/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html data-theme="dark" lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
